-- =====================================================
-- Database Migration: Thought Capture System
-- Adds new columns to the 'ideas' table for the
-- enhanced directive intelligence system
-- =====================================================

-- First, rename 'description' to 'content' if it exists
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'ideas' AND column_name = 'description'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'ideas' AND column_name = 'content'
    ) THEN
        ALTER TABLE ideas RENAME COLUMN description TO content;
    END IF;
END $$;

-- Add content column if neither description nor content exists
ALTER TABLE ideas 
ADD COLUMN IF NOT EXISTS content TEXT;

-- Add status column for Reminder/Directive/High Priority (new status system)
-- Note: This will conflict if you have an existing status column with different values
-- First check if status exists with different values and migrate if needed
DO $$
BEGIN
    -- If status column exists with old values, migrate them
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'ideas' AND column_name = 'status'
    ) THEN
        -- Update old status values to new ones
        UPDATE ideas SET status = 'reminder' WHERE status IN ('active', 'archived', 'implemented', 'discarded');
    END IF;
END $$;

-- Now add or update the status column with proper constraint
ALTER TABLE ideas 
DROP COLUMN IF EXISTS status;

ALTER TABLE ideas 
ADD COLUMN status VARCHAR(20) DEFAULT 'reminder';

-- Add tags column for AI auto-tagging (array of strings)
ALTER TABLE ideas 
ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';

-- Add follow_up_date column for reminder system
ALTER TABLE ideas 
ADD COLUMN IF NOT EXISTS follow_up_date TIMESTAMP WITH TIME ZONE;

-- Add auto_tagged flag to indicate AI tagging
ALTER TABLE ideas 
ADD COLUMN IF NOT EXISTS auto_tagged BOOLEAN DEFAULT FALSE;

-- Add shared_with column (array of staff IDs) if not exists
ALTER TABLE ideas 
ADD COLUMN IF NOT EXISTS shared_with UUID[] DEFAULT '{}';

-- Add archived column if not exists
ALTER TABLE ideas 
ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE;

-- Add signal_cleared column if not exists  
ALTER TABLE ideas 
ADD COLUMN IF NOT EXISTS signal_cleared BOOLEAN DEFAULT FALSE;

-- Add expires_at column if not exists
ALTER TABLE ideas 
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;

-- Create index on status for faster filtering
CREATE INDEX IF NOT EXISTS idx_ideas_status_new ON ideas(status);

-- Create index on follow_up_date for reminder queries
CREATE INDEX IF NOT EXISTS idx_ideas_follow_up_date ON ideas(follow_up_date);

-- Create index on tags for tag-based filtering
CREATE INDEX IF NOT EXISTS idx_ideas_tags ON ideas USING GIN(tags);

-- Create index on shared_with for filtering by shared staff
CREATE INDEX IF NOT EXISTS idx_ideas_shared_with ON ideas USING GIN(shared_with);

-- Create index on archived for filtering
CREATE INDEX IF NOT EXISTS idx_ideas_archived ON ideas(archived);

-- Update existing ideas to have default values
UPDATE ideas 
SET 
    status = COALESCE(status, 'reminder'),
    archived = COALESCE(archived, FALSE),
    shared_with = COALESCE(shared_with, '{}'),
    tags = COALESCE(tags, '{}'),
    auto_tagged = COALESCE(auto_tagged, FALSE),
    signal_cleared = COALESCE(signal_cleared, FALSE)
WHERE status IS NULL 
   OR archived IS NULL 
   OR shared_with IS NULL 
   OR tags IS NULL;

-- =====================================================
-- Optional: Create a view for due reminders
-- =====================================================
CREATE OR REPLACE VIEW due_reminders AS
SELECT 
    id,
    title,
    content,
    status,
    tags,
    follow_up_date,
    auto_tagged,
    created_by,
    shared_with,
    archived,
    created_at,
    CASE 
        WHEN follow_up_date < CURRENT_DATE THEN 'overdue'
        WHEN follow_up_date = CURRENT_DATE THEN 'today'
        WHEN follow_up_date = CURRENT_DATE + INTERVAL '1 day' THEN 'tomorrow'
        ELSE 'future'
    END as urgency
FROM ideas
WHERE follow_up_date IS NOT NULL
  AND archived = FALSE
  AND follow_up_date <= CURRENT_DATE + INTERVAL '1 day';

-- =====================================================
-- Comments for documentation
-- =====================================================
COMMENT ON COLUMN ideas.status IS 'Type of entry: reminder (private), directive (shared), high_priority (urgent)';
COMMENT ON COLUMN ideas.tags IS 'AI-generated category tags (Finance, Marketing, Sales, etc.)';
COMMENT ON COLUMN ideas.follow_up_date IS 'Date when reminder notification should trigger';
COMMENT ON COLUMN ideas.auto_tagged IS 'Whether tags were generated by AI auto-tagging';
